// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nofqfukhbaylpajowxjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vZnFmdWtoYmF5bHBham93eGpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NDM1NTMsImV4cCI6MjA2ODIxOTU1M30.dXEK8WBzv2zT7pqzrgcN8lqUFtCRlsTkTc1fAEnKUDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});